### ISSUE TITLE
Refactor ListDatasetFromDBControls Component with Context API for Better Reusability

### ISSUE THREAD

**Issue by PenHsuanWang** [PenHsuanWang/stock-analyzer-ui#5]
### Description
Currently, `ListDatasetFromDBControls` is tightly coupled with the data prefix it requires to fetch the dataset from the backend. This setup limits the component's reusability across the project. The goal is to refactor `ListDatasetFromDBControls` using the Context API to make it more general and shareable across different pages within the project.

Refactor ListDatasetFromDBControls to Use DataContext

```javascript
// src/components/containers/ListDatasetFromDBControls.js
import React, { useState, useEffect, useContext } from 'react';
import { getListDatasetFromDB } from '../../services/api';
import { DataContext } from '../../contexts/DataContext';
import '../../styles/ListDatasetFromDBControls.css';

const ListDatasetFromDBControls = () => {
  const { prefix } = useContext(DataContext);
  const [data, setData] = useState([]);
  const [selectedData, setSelectedData] = useState([]);

  useEffect(() => {
    // Fetch data using prefix from context
    // ... rest of your useEffect code
  }, [prefix]); // Depend on prefix from context

  // ... rest of your component code remains the same
};

export default ListDatasetFromDBControls;

```

### Tasks
- [ ] Create a `DataContext` to manage the state of the data prefix.
- [ ] Wrap the application in a `DataProvider` to allow any nested component to access the data prefix.
- [ ] Update `ListDatasetFromDBControls` to consume the `DataContext` instead of receiving the prefix as props.
- [ ] Remove any props related to the data prefix passed to `ListDatasetFromDBControls`.
- [ ] Provide a method to update the prefix from the `DataContext` and reflect the new data in `ListDatasetFromDBControls`.

### Expected Behavior
After the refactor:
- `ListDatasetFromDBControls` should not receive a `prefix` prop directly.
- Pages that use `ListDatasetFromDBControls` should be able to dictate the prefix through context.
- It should be easy to set or update the prefix from any page without prop drilling.

**Comment by PenHsuanWang** [comment]
Not to do with Context API but using prop.
